name: Build and Push 
on:
  push:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - run: echo "the repository has been cloned to the runner"
      - name: Build docker container
        run: echo "building the docker container"
  Push:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Pushing the project to the container"